import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Multi part form | React/Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
          <h1>User Register</h1>
          
      </main>
      
    </div>
  )
}